### ISSUE TITLE
Question on project 2 about implicit type casting between int and float

### ISSUE THREAD

**Issue by bzy-debug** [sqlab-sustech/CS323-2021F#10]
What are we supposed to do when an implicit type casting is possible? Should we do an implicit type casting or report an error?
For example, consider below situation:
```
int a, x;
float b, y;
x = a + b;
y = a + b;
```
Should we do implicit type casting form float to int in `x = a + b` and from int to float in `y = a + b` or report an error with type 7 (unmatching operands)?

p.s. Although c does an implicit type casting, I personaly prefer report an error while implicit usually means possible bugs.

**Comment by yepangliu** [comment]
Both are acceptable. If your compiler supports implicit type conversion, you may get some bonus points, as it requires extra engineering work.

**Comment by bzy-debug** [comment]
Thanks! issue closed.
