### ISSUE TITLE
Question about the test case test_2_r04.spl

### ISSUE THREAD

**Issue by bzy-debug** [sqlab-sustech/CS323-2021F#11]
![temp](https://user-images.githubusercontent.com/71200607/142420834-49858001-d6b3-4897-87d0-ebcdb0e58d47.png)

In this test case we are supposed to report an error type 4. However, my compiler reports an extra error:

![image](https://user-images.githubusercontent.com/71200607/142421343-f559528f-3726-4cf4-9ec8-f25f21efce11.png)

This is because the complier resolves the function `compare` as the latest defined one, which is the one defined at line 7.

Is this extra report **OK**?

**Comment by yepangliu** [comment]
It is absolutely ok to report an error at line 15. Please mention your design in the project report.

**Comment by bzy-debug** [comment]
Thanks! issue closed
