### ISSUE TITLE
About the Regular Expression Exercise

### ISSUE THREAD

**Issue by YeeTone** [sqlab-sustech/CS323-2021F#3]
When I tried to finish the programming assignment, I used some websites to help me debug, such as:
https://c.runoob.com/front-end/854/
https://regex101.com/

However, my RegExpression can pass the test on the website, but fail in the judgement by Python.
I wonder why, and here is my regular expression for IPV4:
v4 ((\d|([1-9]\d)|(1\d\d)|(2[0-4]\d)|(25[0-5]))\.){3}(\d|([1-9]\d)|(1\d\d)|(2[0-4]\d)|(25[0-5]))$
https://regex101.com/
![image](https://user-images.githubusercontent.com/64548919/133282864-39ce8578-f4fb-4d98-88bf-aecdb9189993.png)
https://c.runoob.com/front-end/854/
![image](https://user-images.githubusercontent.com/64548919/133282895-f9bbd778-195e-4ede-9d7b-ff035184cd71.png)
LocalJudge:
![image](https://user-images.githubusercontent.com/64548919/133282935-f84bd403-af21-4fe4-bf78-80294d779ab7.png)

**Comment by YeeTone** [comment]
I have already passed all the test cases after 40 mins, by replacing \d by [0-9]. However, I still cannot know the cause of this bug. Prof.Yepang and I sincerely welcome the answer for this question.

**Comment by yepangliu** [comment]
I tried Flex and checked its manual. It seems that Flex indeed does not support "\d" like other regex engines.
