### ISSUE TITLE
How to manage %empty token in project?

### ISSUE THREAD

**Issue by dandansamax** [sqlab-sustech/CS323-2021F#6]
What should I print if a nonterminals match %empty?
For example, if I input a file containing nothing, what will be outputed by our program?
According to the syntax:
```
Program -> ExtDefList
ExtDefList -> ExtDef ExtDefList
| $
```

**Comment by gdjs2** [comment]
As far as I tried, deleting these %empty matching will make a segment fault.

I think these %empty string is used to match the "fathers" in the parser tree.
For instance:
```yacc
StmtList: {
....
}
| Stmt StmtList {
....
}
```
This rules show that the StmtList can be %empty.

There are also many reduction rules which contain StmtList as part of it, like:
```yacc
CompSt: LC DefList StmtList Rc
StmtList: Stmt StmtList
```

I think when necessary, the bison can add some %empty as StmtList to reduces the exists tokens in the stack to CompSt or StmtList. This may make the reduction rules more clear and convenient (I guess).

And when I see the %empty, I will just put a null node at the position. (This null node will not be print out, but it can be the identity of StmtList to help forming the father node). And this seems giving the correct output.

**Comment by dandansamax** [comment]
> reduces the exists tokens at the top of stack in

Thank you so much for your careful reply!!! Now I understand why we should use the empty declaration. 

However, I still confuse about what will be printed if there is no nodes in StmtList  and it matches the %empty token. Should we print the empty token in result?

For example, consider there is a function with no statements in it.
```
int main(){}
```
Shoud we print
```
Specifier
FunDec 
CompSt
  LC 
  DefList 
  StmtList
  RC
```
or
```
Specifier
FunDec 
CompSt
  LC 
  DefList 
  StmtList
    $
  RC
```

**Comment by yepangliu** [comment]
@dandansamax I think the former.

@CirQ Am I right?

**Comment by CirQ** [comment]
Regarding your last question, my answer is: there is no definitely **correct** output. The only purpose of printing the parse tree is to show your parser recognize a syntactically well-formed source program, thus, whether it prints a "nothing" or, literally, nothing should both be acceptable.
Personally, I prefer the former, since it is more concise.

**Comment by dandansamax** [comment]
> Regarding your last question, my answer is: there is no definitely **correct** output. The only purpose of printing the parse tree is to show your parser recognize a syntactically well-formed source program, thus, whether it prints a "nothing" or, literally, nothing should both be acceptable. Personally, I prefer the former, as @yepangliu suggested, since it is more concise.

Ok, I understand.

Thank you so much!
