### ISSUE TITLE
A question about output format

### ISSUE THREAD

**Issue by dandansamax** [sqlab-sustech/CS323-2021F#8]
After checking given example outputs, I found something confused about output format.

Consider this piece of spl code:
```c
int main(){
    a=1;
    b=1;
}
```
I think the output will be:
```
Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        TYPE: int
      FunDec (1)
        ID: main
        LP
        RP
      CompSt (1)
        LC
        StmtList (2)
          Stmt (2)
            Exp (2)
              Exp (2)
                ID: a
              ASSIGN
              Exp (2)
                INT: 1
            SEMI
          Stmt (3)
            Exp (3)
              Exp (3)
                ID: b
              ASSIGN
              Exp (3)
                INT: 1
            SEMI
        RC
```
However, example outputs tell me it should be:
```
Program (1)
  ExtDefList (1)
    ExtDef (1)
      Specifier (1)
        TYPE: int
      FunDec (1)
        ID: main
        LP
        RP
      CompSt (1)
        LC
        StmtList (2)
          Stmt (2)
            Exp (2)
              Exp (2)
                ID: a
              ASSIGN
              Exp (2)
                INT: 1
            SEMI
          StmtList (3)
            Stmt (3)
              Exp (3)
                Exp (3)
                  ID: b
                ASSIGN
                Exp (3)
                  INT: 1
              SEMI
        RC
```
The reason of the difference is that I think Stmt (2) and Stmt (3) should under same StmtList because logically they are coordinate, but example outputs strictly follow the syntax we defined in syntax.y and make them under different StmtList.

My problem is if my point of view acceptable for judgement? If yes, how do we grade our project since everyone has their own understanding of output format.

Thank you!

**Comment by yepangliu** [comment]
The production rule that generates statements is: StmtList -> Stmt StmtList

So the derivation corresponding to your input program is: StmtList => Stmt StmtList => Stmt Stmt StmtList => Stmt Stmt. In your first output, the StmtList symbol directly generates two "Stmt" symbols, for which we cannot find any production rule in our grammar.

**Comment by yepangliu** [comment]
The production rule that generates statements is: StmtList -> Stmt StmtList

So the derivation corresponding to your input program is: StmtList => Stmt StmtList => Stmt Stmt StmtList => Stmt Stmt. In your first output, the StmtList symbol directly generates two "Stmt" symbols, for which we cannot find any production rule in our grammar.

**Comment by dandansamax** [comment]
I understood, thank you!
